/**
 * Generates the cross-platform crypto test vectors from the SAME code path the
 * browser uses (WebCrypto `crypto.subtle`), so the Swift side is checked against
 * the web implementation rather than against a second hand-written spec.
 *
 * Run:  node macos/scripts/gen-vectors.mjs
 * Out:  macos/GembaKit/Tests/GembaCryptoTests/vectors.json
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const AES_KEY_BITS = 128;
const IV_BYTES = 12;

function toBase64Url(bytes) {
  return Buffer.from(bytes).toString("base64")
    .replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}
function fromBase64Url(s) {
  let b64 = s.replace(/-/g, "+").replace(/_/g, "/");
  while (b64.length % 4) b64 += "=";
  return new Uint8Array(Buffer.from(b64, "base64"));
}

async function generateKey() {
  return crypto.subtle.generateKey({ name: "AES-GCM", length: AES_KEY_BITS }, true, ["encrypt", "decrypt"]);
}
async function exportKeyBase64(key) {
  return toBase64Url(new Uint8Array(await crypto.subtle.exportKey("raw", key)));
}
async function encryptPacked(data, key) {
  const iv = crypto.getRandomValues(new Uint8Array(IV_BYTES));
  const ciphertext = await crypto.subtle.encrypt({ name: "AES-GCM", iv }, key, data);
  const out = new Uint8Array(IV_BYTES + ciphertext.byteLength);
  out.set(iv, 0);
  out.set(new Uint8Array(ciphertext), IV_BYTES);
  return out;
}
async function sha256Hex(input) {
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(input));
  return Array.from(new Uint8Array(digest)).map((b) => b.toString(16).padStart(2, "0")).join("");
}

/** WebCrypto caps getRandomValues at 64 KiB per call — fill in chunks. */
function randomBytes(n) {
  const out = new Uint8Array(n);
  for (let i = 0; i < n; i += 65536) {
    out.set(crypto.getRandomValues(new Uint8Array(Math.min(65536, n - i))), i);
  }
  return out;
}

const cases = [
  { name: "empty", bytes: new Uint8Array(0) },
  { name: "one-byte", bytes: new Uint8Array([0x00]) },
  { name: "ascii", bytes: new TextEncoder().encode("hello gemba filesend") },
  { name: "utf8-emoji", bytes: new TextEncoder().encode("café — 文件 — 🔐 end-to-end") },
  { name: "all-byte-values", bytes: new Uint8Array(Array.from({ length: 256 }, (_, i) => i)) },
  { name: "block-aligned-1024", bytes: randomBytes(1024) },
  { name: "unaligned-4095", bytes: randomBytes(4095) },
  // 64 KiB: large enough to cross many internal block boundaries, small
  // enough that the committed vectors file stays in the low hundreds of KB.
  { name: "large-64kib", bytes: randomBytes(64 * 1024) },
];

const vectors = [];
for (const c of cases) {
  const key = await generateKey();
  const keyB64 = await exportKeyBase64(key);
  const packed = await encryptPacked(c.bytes.buffer ? c.bytes.slice().buffer : c.bytes, key);
  // Round-trip here too, so a broken generator can never emit a "passing" vector.
  const back = new Uint8Array(await crypto.subtle.decrypt(
    { name: "AES-GCM", iv: packed.slice(0, IV_BYTES) },
    key,
    packed.slice(IV_BYTES),
  ));
  if (Buffer.compare(Buffer.from(back), Buffer.from(c.bytes)) !== 0) {
    throw new Error(`generator round-trip failed for ${c.name}`);
  }
  vectors.push({
    name: c.name,
    keyBase64Url: keyB64,
    plaintextBase64: Buffer.from(c.bytes).toString("base64"),
    packedBase64: Buffer.from(packed).toString("base64"),
    plaintextLength: c.bytes.length,
  });
}

// base64url edge cases: byte patterns that exercise +/ -> -_ and every padding length.
const base64UrlCases = [];
for (const raw of [[0xfb, 0xff, 0xbf], [0x00], [0x00, 0x01], [0xff, 0xfe, 0xfd, 0xfc], [0x3e, 0x3f]]) {
  const bytes = new Uint8Array(raw);
  base64UrlCases.push({ bytesBase64: Buffer.from(bytes).toString("base64"), encoded: toBase64Url(bytes) });
}

// Password hashing parity: sha256Hex(password + salt), the exact server formula.
const passwordCases = [];
for (const [password, salt] of [["hunter2", "abcDEF-_123456789012345"], ["", "c2FsdA"], ["pässwörd 🔑", "zzz"]]) {
  passwordCases.push({ password, salt, sha256Hex: await sha256Hex(password + salt) });
}

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "..", "GembaKit", "Tests", "GembaCryptoTests", "vectors.json");
writeFileSync(out, JSON.stringify({
  note: "Generated by macos/scripts/gen-vectors.mjs from the web WebCrypto path. Do not hand-edit.",
  generatedAt: new Date().toISOString(),
  vectors, base64UrlCases, passwordCases,
}, null, 2));
console.log(`wrote ${out} (${vectors.length} vectors)`);

// Sanity: verify base64url decode is lossless for every vector key.
for (const v of vectors) {
  if (toBase64Url(fromBase64Url(v.keyBase64Url)) !== v.keyBase64Url) {
    throw new Error("base64url round-trip broken");
  }
}
